[project]
name = "dc-dns"
version = "0.1.0"
description = "DNS lookup plugin for demon-cry"
authors = [
    {name = "mooncore-inc"}
]
license = "Apache2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "demon-cry-base==0.6.0",
    "dnspython>=2.0.0,<3.0.0"
]

[project.entry-points."demon_cry.plugins"]
dns_lookup = "dc_dns:DnsLookup"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
